### ISSUE TITLE
签名不过 

### ISSUE THREAD

**Issue by a512532593** [vcheckzen/FamilyCloudSpeederInShell#1]
*******************************************
Sending heart_beat package <1>
heart_beat:<signature:C751410AAF3E8F3835911D23A280D20E578CA2CF>
date:<五, 19 4月 2019 07:48:05 GMT>
status_code:400
response:
<?xml version="1.0" encoding="UTF-8"?> <error> <code>InvalidArgument</code> <message>sessionsignature is not match</message> </error>
Sending heart_beat package <1> failed
*******************************************

**Comment by vcheckzen** [comment]
感谢反馈，应该是时间有中文导致的，马上更新一下

**Comment by a512532593** [comment]
perfect 可以了

**Comment by a512532593** [comment]
顺便问一下 如果免费的600分钟用完 提速是不是就失效了

**Comment by vcheckzen** [comment]
是，不过貌似这个接口不扣时常

**Comment by a512532593** [comment]
好像还真是 我一会测试观察一下 感谢
