### ISSUE TITLE
macOS运行出错。uuid这个文件没有？

### ISSUE THREAD

**Issue by ghost** [vcheckzen/FamilyCloudSpeederInShell#10]
*******************************************
Sending heart_beat package <1>
cat: /proc/sys/kernel/random/uuid: No such file or directory
heart_beat:<signature:XXXXXXXXXXXXXXXXXXXXXXXXXX>
date:<Wed, 22 May 2019 04:07:13 GMT>
response:
<?xml version="1.0" encoding="UTF-8"?>
<error>
   <code>InvalidArgument</code>
   <message>date/accessToken/sessionKey/signature is null</message>
</error>
Sending heart_beat package <1> failed
*******************************************

**Comment by vcheckzen** [comment]
方便的话，通过上个 issue 提供的联系联系方式加我，协助测试，谢谢
