### ISSUE TITLE
西安电信无法正确运行

### ISSUE THREAD

**Issue by abc9878** [vcheckzen/FamilyCloudSpeederInShell#12]
无法获取session_key，获取session_key的上一步result获取到的信息是“<?xml version="1.0" encoding="UTF-8"?>
<error><code>UserInvalidOpenToken</code><message>error in login get unifyAccountInfo is null</message></error>”，导致获取session_key失败。

**Comment by vcheckzen** [comment]
抓包或参数填写错误，按照 wiki 说明抓天翼云盘的指定请求
