### ISSUE TITLE
wiki里面只有如何安装，请问如何卸载或者暂停呢？谢谢

### ISSUE THREAD

**Issue by ACvsRM** [vcheckzen/FamilyCloudSpeederInShell#15]
今天晚上8点左右，已经失效了，等待您的更新。

另外就是如果我想暂停或者卸载掉这个shell，请问该如何处理。小白一个，见笑了

**Comment by naicfeng** [comment]
直接结束进程即可啊，卸载就删掉。
计划任务运行的就删掉计划任务。
自动启动的就删掉启动项。

**Comment by ACvsRM** [comment]
> 直接结束进程即可啊，卸载就删掉。
> 计划任务运行的就删掉计划任务。
> 自动启动的就删掉启动项。

小白一个，没找到对应的位置。
忘了说我的环境了，K2P pandorabox 19.02
昨天怕一直挂着出问题，修改/root/CloudDisk下的speedup_router.sh的文件名为speedup_router1.sh
结果看系统日志还是会10分钟启动一次（尽管我知道启动失败了）
USER root pid 19298 cmd /root/CloudDisk/speedup_router.sh

1、在路由器的系统进程里没有找到具体的进程，请问是哪个进程。
![image](https://user-images.githubusercontent.com/51409398/59014448-37c64980-886f-11e9-96c5-b2b3dbae9db0.png)
卸载删掉是指直接把/root/CloudDisk这个文件夹删掉吗？

2、计划任务里面只有我自己写的一个计划任务
![2](https://user-images.githubusercontent.com/51409398/59015593-ec616a80-8871-11e9-875d-c94978621852.jpg)

**Comment by vcheckzen** [comment]
有时间我更新个卸载脚本，你先保持原样，影响不大

**Comment by vcheckzen** [comment]
[卸载脚本](https://github.com/vcheckzen/FamilyCloudSpeederInShell/wiki/%E8%84%9A%E6%9C%AC%E5%8D%B8%E8%BD%BD)
