### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Warm-rain** [vcheckzen/FamilyCloudSpeederInShell#2]
![~7P`QZ(8$0GZ6K()~9{5T6A](https://user-images.githubusercontent.com/31696282/56417509-c3d3e000-62c6-11e9-9040-ce7eeb8bc545.png)
提示这个怎么解决

**Comment by vcheckzen** [comment]
```bash
opkg update && opkg install coreutils-nohup libreadline libcurl libopenssl bash curl wget openssl-util ca-certificates ca-bundle
```

**Comment by Warm-rain** [comment]
![~F140B 3I_78RIHVD`($D(F](https://user-images.githubusercontent.com/31696282/56417936-0ba73700-62c8-11e9-9d21-df901d92c6b7.png)
郁闷了

**Comment by vcheckzen** [comment]
你用的是什么系统那

**Comment by Warm-rain** [comment]
![6$B}DE}(K5RPACLREOL5%~F](https://user-images.githubusercontent.com/31696282/56418132-a6077a80-62c8-11e9-8f42-d8368008e315.png)
这两个

**Comment by vcheckzen** [comment]
第一个感觉固件有问题，没法更新😀，第二个是 armbian 还是 openwrt ，加下我 `base64.decode(UVE6MzMxOTE0OTEw)` 详细看一下
