### ISSUE TITLE
sessionsignature is not match 这是说登陆信息不匹配吗？

### ISSUE THREAD

**Issue by SCGabriel** [vcheckzen/FamilyCloudSpeederInShell#3]
response:
<?xml version="1.0" encoding="UTF-8"?> <error> <code>InvalidArgument</code> <message>sessionsignature is not match</message> </error>
Sending heart_beat package <1> failed

这是按照
https://github.com/aiyijing/familycloudaccelerate/wiki/%E5%AE%B6%E5%BA%AD%E4%BA%91%E6%89%8B%E6%9C%BA%E7%AB%AF%E6%8A%93%E5%8C%85%E6%96%B9%E6%B3%95
这个教程获取的

**Comment by vcheckzen** [comment]
把结果全部贴出来一下，还有确定一下抓包参数

**Comment by vcheckzen** [comment]
这里我可能不能第一时间看到，上个 issue 有我的联系方式，着急可以加一下
