### ISSUE TITLE
新版本的 accessToken 应该抓取哪个？

### ISSUE THREAD

**Issue by Iy204** [vcheckzen/FamilyCloudSpeederInShell#5]
`Wiki` 上还是 `session_key` 和 `session_secret`

**Comment by vcheckzen** [comment]
# 参数抓取

`家庭云 FamilyCloud` 与 `天翼云盘 CloudDisk` 版使用同一 `accessToken`，但必须从 `天翼云盘 App` 抓取，`家庭云` 无效。包含该参数的请求如下：

```txt
api.cloud.189.cn/login4MergedClient.action
api.cloud.189.cn/loginByOpen189AccessToken.action
```

注意：
- 需要开通云盘会员
- 无需上传文件测速，登录后便可停止抓包
- `Android 7.0` 以上须使用 [平行空间 ](https://github.com/MegatronKing/HttpCanary/tree/master/docs/v2/zh-CN#22-%E7%AC%AC%E4%B8%89%E6%96%B9app%E6%8A%93%E5%8C%85) 或模拟器抓取 `HTTPS`

# 测试运行

路由系统必须按照 `README` 说明无差别执行依赖安装命令，因为即使系统自带部分依赖，功能也可能不完整。`老毛子 Padavan`、`梅林 Asuswrt-merlin` 需要事先打开 `opt` 环境，并且可能需要指定 `bash` 解释器，即使用 `/opt/bin/bash speedup.sh` 命令执行

需要说明的是，无内存卡或 U 盘的 `老毛子 Padavan`，断电后会丢失 `opt` 环境，因此需要在开机后重新安装依赖，执行一次以下命令即可实现开机自动安装

```bash
object="/etc/storage/script/Sh99_install_requirements_for_clouddisk.sh" && \
echo -e "#!/bin/sh\n\
# copyright by logi\n\
source /etc/storage/script/init.sh\n\
while [[ ! -f /opt/bin/opkg ]]\n\
do\n\
   sleep 60\n\
   logger -t 'CloudDisk' 'No opt, sleep 60s.'\n\
done\n\
logger -t 'CloudDisk' 'Start install requirements.'\n\
opkg update && opkg install \\
coreutils-nohup libreadline libcurl \\
libopenssl bash curl wget openssl-util ca-certificates ca-bundle\n\
logger -t 'CloudDisk' 'Requiremetns installed.'"\
> "$object" && chmod +x "$object"
```

对于脚本保存目录，`老毛子 Padavan` 建议上传到 `/etc/storage`，修改完毕后执行 `mtd_storage.sh save`。`梅林 Asuswrt-merlin` 上传到 `/jffs` 目录

以下为正常输出（两版接口来自不同 `App`，任选其一运行即可）：

```txt
# 天翼云盘
[root@LOGI:/usr/local/etc/FamilyCloudSpeederInShell/beta/CloudDisk]#./speedup.sh 
*******************************************
Sending heart_beat package <1>
heart_beat:<signature:E5AF42E9B7FF419E3E37F0DF13AEB04CF4C151AA>
date:<Tue, 07 May 2019 13:14:24 GMT>
response:
<?xml version="1.0" encoding="UTF-8"?>
<qosInfoResponse><dialAccount>xx::xxxxxxxxxxxx</dialAccount><baseDownRate>20480</baseDownRate><baseUpRate>4096</baseUpRate><targetDownRate>512000</targetDownRate><targetUpRate>51200</targetUpRate><dialAbility>1</dialAbility><qosSn>151232638822767107</qosSn></qosInfoResponse>
Sending heart_beat package <1> succeeded
*******************************************

# 家庭云
[root@LOGI:/usr/local/etc/FamilyCloudSpeederInShell/beta/FamilyCloud]#./speedup.sh 
*******************************************
Sending heart_beat package <1>
heart_beat:<signature:6472E77A29FC8EED505B393C65D4EEECE968119B>
date:<Tue, 07 May 2019 13:17:20 GMT>
status_code:400
response:
<?xml version="1.0" encoding="UTF-8"?> <error><code>FamilySpeedTimeOver</code><message>open() - requestId=eae17814-0153-4a49-9490-d87c65d407f5,sessionKey=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_family,port=58043,clientIp=xxx.xxx.xxx.xxx,dialAcct=xx::xxxxxxxxxxxx, family speed time over,B44DAA8236AF77FB3F6D1E4CE9EC03FDB7045CE6BE0004A6B8F0135B23176119A99F860989E82C98B16DBCBF6AAE4ECFCF9F539D3C009DF578B0CA46F28B03B1FFD23E418748A9F3,B44DAA8236AF77FB3F6D1E4CE9EC03FDB7045CE6BE0004A6B8F0135B23176119A99F860989E82C98B16DBCBF6AAE4ECFCF9F539D3C009DF578B0CA46F28B03B1FFD23E418748A9F3</message></error>
Sending heart_beat package <1> succeeded
*******************************************
```

# 开机自启

对于开机自启，`老毛子 Padavan`、`梅林 Asuswrt-merlin` 可以在 `wan-start` 脚本中追加命令

 ```bash
if [[ "`ps | grep speedup | grep -v grep`" == "" ]];
then
   # xxx 改成脚本所在路径
    nohup /opt/bin/bash /xxx/speedup.sh > /dev/null 2>&1 &
fi
```

`OpenWrt` 、`LEDE`、`Pandorabox` 和其他 `类 OP` 固件在  `/etc/rc.local` 文件 `exit` 前追加上述命令，且不需要指定 `bash` 解释器

# 定时任务

你也可以按照 `README` 说明添加`定时任务`，`定时任务`和`开机自启`二选一，不要重复添加。路由系统推荐使用`定时任务`版，因其可打印 `log` 到系统日志，也无需担心进程误杀。需要注意的是 `Pandorabox` 默认禁用了 `cron`，需要使用以下命令开启

```bash
/etc/init.d/cron enable && /etc/init.d/cron start
```

# 领取空间

制作了 [天翼云盘领空间.har.gz](https://github.com/vcheckzen/FamilyCloudSpeederInShell/files/3193941/har.gz) 模板，到 [该网站](https://qiandao.xxkwz.cn) 注册，去掉 `.gz` 后缀，上传自定义模板并创建任务即可
![批注 2019-05-08 130127](https://user-images.githubusercontent.com/18008498/57350630-6c23e880-7191-11e9-92f7-de5267fbefb8.jpg)

# 讨论交流

你可通过 [QQ](http://wpa.qq.com/msgrd?v=3&uin=331914910&site=qq&menu=yes) 与我联系，也可加入 [TG 群组](https://t.me/pubg2333) 持续讨论 `Linux、Router 和 Network` 相关话题

**Comment by Iy204** [comment]
`root@openwrt:/etc/FamilyCloud# ./speedup.sh 
*******************************************
Sending heart_beat package <1>
heart_beat:<signature:E68F8D4FFF634F347983B676EA04301E7403EB8A>
date:<Tue, 07 May 2019 10:19:55 GMT>
status_code:400
response:
<?xml version="1.0" encoding="UTF-8"?> <error> <code>InvalidArgument</code> <message>date/accessToken/sessionKey/signature is null</message> </error>
Sending heart_beat package <1> failed
*******************************************
`
Fj电信新版本的脚本不成功。

**Comment by vcheckzen** [comment]
关掉重新运行，也可以试试 CloudDisk 版本

**Comment by vcheckzen** [comment]
欢迎 Star 并持续反馈
