### ISSUE TITLE
运行时提示utils.sh第十行 syntax error: unexpected "(" (expecting "}")

### ISSUE THREAD

**Issue by November-raining** [vcheckzen/FamilyCloudSpeederInShell#6]
平台MT7621 华硕老毛子  安装了bash
不论sh  ash  bash运行均会报此错误，脚本第一行确实定义了bash环境，搜索了下暂时没找到解决办法

**Comment by vcheckzen** [comment]
把 `README` 的依赖安装命令执行一遍，无论原来有没有。嵌入式环境的 `bash` 功能可能不完整，需要具体看，通过上一条 `issue` 联系我
