### ISSUE TITLE
提速不成功

### ISSUE THREAD

**Issue by vyronjo** [vcheckzen/FamilyCloudSpeederInShell#8]
用的CloudDisk版的，Charles抓的包。

![image](https://user-images.githubusercontent.com/26548394/57963811-c7f22c80-795c-11e9-92e1-e8e3383f9f42.png)
![image](https://user-images.githubusercontent.com/26548394/57963826-ef48f980-795c-11e9-94db-9a0f7c536913.png)
![image](https://user-images.githubusercontent.com/26548394/57963829-fc65e880-795c-11e9-8730-31021be173fb.png)

**Comment by vcheckzen** [comment]
未开会员?

**Comment by vyronjo** [comment]
> 未开会员?

开了的，昨天之前都用的那种start+check的脚本，能成功提速的。昨天开始失效了

**Comment by vyronjo** [comment]
![image](https://user-images.githubusercontent.com/26548394/57963977-aa729200-795f-11e9-8258-360d12470d67.png)

**Comment by vcheckzen** [comment]
用 FamilyCloud 版本测试，贴结果出来

**Comment by vyronjo** [comment]
FamilyCloud版结果
![image](https://user-images.githubusercontent.com/26548394/57964102-11914600-7962-11e9-8846-194bfa943738.png)

这看起来好像是宽带帐号都没获取到？
但是
![image](https://user-images.githubusercontent.com/26548394/57964091-e4449800-7961-11e9-8a45-7b4bf52c3819.png)
这里看起来是能获取到宽带帐号的

**Comment by vcheckzen** [comment]
加我远程看看？置顶 issue 联系
